[package]
edition = "2024"
name = "compressed-mat-vec-mul"
publish = false
rust-version = "1.85"
version = "0.0.1"

[dependencies]
bytemuck = "1"
clap = {version = "4.5.32", features = ["derive"]}
clap-verbosity-flag = "3.0.2"
env_logger = "0.11.6"
log = "0.4.26"
pollster = "0.4"
wgpu = "24.0.0"
